testImplications <- function( covariance.matrix, sample.size ){
	library(ggm)
	tst <- function(i){ pcor.test( pcor(i,covariance.matrix), length(i)-2, sample.size )$pvalue }
tos <- function(i){ paste(i,collapse=" ") }
implications <- list(c("GFP expression","OD","cell_population"),
		c("GFP expression","OD","growth_rate"),
		c("GFP expression","OD","genetic_background"),
		c("GFP expression","OD","expression_capacity"),
		c("GFP expression","cell_population","growth_rate"),
		c("GFP expression","cell_population","genetic_background"),
		c("GFP expression","cell_population","expression_capacity"),
		c("GFP expression","cellular_capacity","growth_rate","productivity"),
		c("GFP expression","cellular_capacity","genetic_background","productivity"),
		c("GFP expression","cellular_capacity","expression_capacity","productivity"),
		c("GFP expression","cumate_induction"),
		c("GFP expression","genetic_background","expression_capacity"),
		c("GFP expression","growth_rate","genetic_background"),
		c("GFP expression","growth_rate","expression_capacity"),
		c("GFP expression","plate_reader"),
		c("GFP expression","proteome","expression_capacity"),
		c("LFQ","OD","cell_population"),
		c("LFQ","OD","growth_rate"),
		c("LFQ","OD","genetic_background"),
		c("LFQ","OD","expression_capacity"),
		c("LFQ","OD","GFP expression"),
		c("LFQ","cell_population","growth_rate"),
		c("LFQ","cell_population","genetic_background"),
		c("LFQ","cell_population","expression_capacity"),
		c("LFQ","cell_population","GFP expression"),
		c("LFQ","cellular_capacity","growth_rate","productivity"),
		c("LFQ","cellular_capacity","genetic_background","productivity"),
		c("LFQ","cellular_capacity","expression_capacity","productivity"),
		c("LFQ","cellular_capacity","GFP expression"),
		c("LFQ","cumate_induction"),
		c("LFQ","expression_capacity","GFP expression"),
		c("LFQ","fluorescence","GFP expression"),
		c("LFQ","genetic_background","expression_capacity"),
		c("LFQ","genetic_background","GFP expression"),
		c("LFQ","growth_rate","genetic_background"),
		c("LFQ","growth_rate","expression_capacity"),
		c("LFQ","growth_rate","GFP expression"),
		c("LFQ","iBAQ","GFP expression"),
		c("LFQ","plate_reader"),
		c("LFQ","productivity","GFP expression"),
		c("LFQ","proteome","expression_capacity"),
		c("LFQ","proteome","GFP expression"),
		c("OD","cellular_capacity","growth_rate"),
		c("OD","cellular_capacity","cell_population"),
		c("OD","cumate_induction","growth_rate"),
		c("OD","cumate_induction","cell_population"),
		c("OD","expression_capacity","genetic_background"),
		c("OD","expression_capacity","growth_rate"),
		c("OD","expression_capacity","cell_population"),
		c("OD","genetic_background","growth_rate"),
		c("OD","genetic_background","cell_population"),
		c("OD","growth_rate","cell_population"),
		c("OD","iBAQ","GFP expression","proteome"),
		c("OD","iBAQ","expression_capacity"),
		c("OD","iBAQ","genetic_background"),
		c("OD","iBAQ","growth_rate"),
		c("OD","iBAQ","cell_population"),
		c("OD","plate_reader"),
		c("OD","productivity","GFP expression","proteome"),
		c("OD","productivity","expression_capacity"),
		c("OD","productivity","genetic_background"),
		c("OD","productivity","growth_rate"),
		c("OD","productivity","cell_population"),
		c("OD","proteome","expression_capacity"),
		c("OD","proteome","genetic_background"),
		c("OD","proteome","growth_rate"),
		c("OD","proteome","cell_population"),
		c("cell_population","cellular_capacity","growth_rate"),
		c("cell_population","cumate_induction","growth_rate"),
		c("cell_population","expression_capacity","genetic_background"),
		c("cell_population","expression_capacity","growth_rate"),
		c("cell_population","fluorescence","GFP expression","OD"),
		c("cell_population","fluorescence","OD","expression_capacity"),
		c("cell_population","fluorescence","genetic_background","OD"),
		c("cell_population","fluorescence","growth_rate","OD"),
		c("cell_population","genetic_background","growth_rate"),
		c("cell_population","iBAQ","GFP expression","proteome"),
		c("cell_population","iBAQ","expression_capacity"),
		c("cell_population","iBAQ","genetic_background"),
		c("cell_population","iBAQ","growth_rate"),
		c("cell_population","plate_reader"),
		c("cell_population","productivity","GFP expression","proteome"),
		c("cell_population","productivity","expression_capacity"),
		c("cell_population","productivity","genetic_background"),
		c("cell_population","productivity","growth_rate"),
		c("cell_population","proteome","expression_capacity"),
		c("cell_population","proteome","genetic_background"),
		c("cell_population","proteome","growth_rate"),
		c("cellular_capacity","cumate_induction","genetic_background","growth_rate"),
		c("cellular_capacity","cumate_induction","expression_capacity","growth_rate"),
		c("cellular_capacity","cumate_induction","proteome","GFP expression","growth_rate"),
		c("cellular_capacity","cumate_induction","productivity","growth_rate"),
		c("cellular_capacity","expression_capacity","genetic_background","proteome","GFP expression"),
		c("cellular_capacity","expression_capacity","productivity","genetic_background"),
		c("cellular_capacity","expression_capacity","growth_rate","proteome","GFP expression"),
		c("cellular_capacity","expression_capacity","growth_rate","productivity"),
		c("cellular_capacity","fluorescence","GFP expression","OD"),
		c("cellular_capacity","fluorescence","GFP expression","cell_population"),
		c("cellular_capacity","fluorescence","productivity","expression_capacity","OD"),
		c("cellular_capacity","fluorescence","productivity","expression_capacity","cell_population"),
		c("cellular_capacity","fluorescence","productivity","genetic_background","OD"),
		c("cellular_capacity","fluorescence","productivity","genetic_background","cell_population"),
		c("cellular_capacity","fluorescence","growth_rate","GFP expression"),
		c("cellular_capacity","fluorescence","growth_rate","productivity"),
		c("cellular_capacity","genetic_background","growth_rate","expression_capacity"),
		c("cellular_capacity","genetic_background","growth_rate","proteome","GFP expression"),
		c("cellular_capacity","genetic_background","productivity","growth_rate"),
		c("cellular_capacity","iBAQ","GFP expression","proteome"),
		c("cellular_capacity","iBAQ","expression_capacity","productivity"),
		c("cellular_capacity","iBAQ","genetic_background","productivity"),
		c("cellular_capacity","iBAQ","growth_rate","productivity"),
		c("cellular_capacity","plate_reader"),
		c("cellular_capacity","proteome","productivity","expression_capacity"),
		c("cellular_capacity","proteome","productivity","genetic_background"),
		c("cellular_capacity","proteome","growth_rate","productivity"),
		c("cumate_induction","expression_capacity"),
		c("cumate_induction","fluorescence","GFP expression","OD"),
		c("cumate_induction","fluorescence","OD","expression_capacity"),
		c("cumate_induction","fluorescence","GFP expression","cell_population"),
		c("cumate_induction","fluorescence","cell_population","expression_capacity"),
		c("cumate_induction","fluorescence","growth_rate","GFP expression"),
		c("cumate_induction","fluorescence","growth_rate","expression_capacity"),
		c("cumate_induction","fluorescence","genetic_background","OD"),
		c("cumate_induction","fluorescence","genetic_background","cell_population"),
		c("cumate_induction","fluorescence","genetic_background","growth_rate"),
		c("cumate_induction","genetic_background"),
		c("cumate_induction","iBAQ"),
		c("cumate_induction","plate_reader"),
		c("cumate_induction","productivity"),
		c("cumate_induction","proteome"),
		c("expression_capacity","fluorescence","GFP expression","OD"),
		c("expression_capacity","fluorescence","GFP expression","cell_population"),
		c("expression_capacity","fluorescence","growth_rate","GFP expression"),
		c("expression_capacity","fluorescence","genetic_background","GFP expression"),
		c("expression_capacity","growth_rate","genetic_background"),
		c("expression_capacity","iBAQ","GFP expression","proteome"),
		c("expression_capacity","plate_reader"),
		c("expression_capacity","productivity","GFP expression","proteome"),
		c("fluorescence","genetic_background","growth_rate","expression_capacity"),
		c("fluorescence","genetic_background","cell_population","expression_capacity"),
		c("fluorescence","genetic_background","OD","expression_capacity"),
		c("fluorescence","genetic_background","GFP expression","growth_rate"),
		c("fluorescence","genetic_background","GFP expression","cell_population"),
		c("fluorescence","genetic_background","OD","GFP expression"),
		c("fluorescence","growth_rate","genetic_background","cell_population"),
		c("fluorescence","growth_rate","expression_capacity","cell_population"),
		c("fluorescence","growth_rate","OD","genetic_background"),
		c("fluorescence","growth_rate","OD","expression_capacity"),
		c("fluorescence","growth_rate","GFP expression","cell_population"),
		c("fluorescence","growth_rate","GFP expression","OD"),
		c("fluorescence","iBAQ","GFP expression","proteome"),
		c("fluorescence","iBAQ","GFP expression","expression_capacity"),
		c("fluorescence","iBAQ","genetic_background","GFP expression"),
		c("fluorescence","iBAQ","growth_rate","GFP expression"),
		c("fluorescence","iBAQ","cell_population","GFP expression"),
		c("fluorescence","iBAQ","OD","GFP expression"),
		c("fluorescence","productivity","GFP expression","proteome"),
		c("fluorescence","productivity","GFP expression","expression_capacity"),
		c("fluorescence","productivity","genetic_background","GFP expression"),
		c("fluorescence","productivity","growth_rate","GFP expression"),
		c("fluorescence","productivity","cell_population","GFP expression"),
		c("fluorescence","productivity","OD","GFP expression"),
		c("fluorescence","proteome","expression_capacity"),
		c("fluorescence","proteome","genetic_background","GFP expression"),
		c("fluorescence","proteome","growth_rate","GFP expression"),
		c("fluorescence","proteome","cell_population","GFP expression"),
		c("fluorescence","proteome","OD","GFP expression"),
		c("genetic_background","iBAQ","GFP expression","proteome"),
		c("genetic_background","iBAQ","expression_capacity"),
		c("genetic_background","plate_reader"),
		c("genetic_background","productivity","GFP expression","proteome"),
		c("genetic_background","productivity","expression_capacity"),
		c("genetic_background","proteome","expression_capacity"),
		c("growth_rate","iBAQ","GFP expression","proteome"),
		c("growth_rate","iBAQ","expression_capacity"),
		c("growth_rate","iBAQ","genetic_background"),
		c("growth_rate","plate_reader"),
		c("growth_rate","productivity","GFP expression","proteome"),
		c("growth_rate","productivity","expression_capacity"),
		c("growth_rate","productivity","genetic_background"),
		c("growth_rate","proteome","expression_capacity"),
		c("growth_rate","proteome","genetic_background"),
		c("iBAQ","plate_reader"),
		c("iBAQ","productivity","GFP expression","proteome"),
		c("plate_reader","productivity"),
		c("plate_reader","proteome"))
	data.frame( implication=unlist(lapply(implications,tos)),
		pvalue=unlist( lapply( implications, tst ) ) )

}
