testImplications <- function( covariance.matrix, sample.size ){
	library(ggm)
	tst <- function(i){ pcor.test( pcor(i,covariance.matrix), length(i)-2, sample.size )$pvalue }
tos <- function(i){ paste(i,collapse=" ") }
implications <- list(c("GFP expression","OD","cell_population"),
		c("GFP expression","OD","growth_rate"),
		c("GFP expression","OD","genetic_background"),
		c("GFP expression","OD","expression_capacity"),
		c("GFP expression","cell_population","growth_rate"),
		c("GFP expression","cell_population","genetic_background"),
		c("GFP expression","cell_population","expression_capacity"),
		c("GFP expression","cellular_capacity","growth_rate","productivity"),
		c("GFP expression","cellular_capacity","genetic_background","productivity"),
		c("GFP expression","cellular_capacity","expression_capacity","productivity"),
		c("GFP expression","cumate_induction"),
		c("GFP expression","genetic_background","expression_capacity"),
		c("GFP expression","growth_rate","genetic_background"),
		c("GFP expression","growth_rate","expression_capacity"),
		c("GFP expression","plate_reader"),
		c("GFP expression","proteome_expression","expression_capacity"),
		c("GFP expression","proteome_iBAQ","proteome_expression"),
		c("GFP expression","proteome_iBAQ","expression_capacity"),
		c("GFP_LFQ","GFP_fluorescence","GFP expression"),
		c("GFP_LFQ","GFP_iBAQ","GFP expression"),
		c("GFP_LFQ","OD","cell_population"),
		c("GFP_LFQ","OD","growth_rate"),
		c("GFP_LFQ","OD","genetic_background"),
		c("GFP_LFQ","OD","expression_capacity"),
		c("GFP_LFQ","OD","GFP expression"),
		c("GFP_LFQ","cell_population","growth_rate"),
		c("GFP_LFQ","cell_population","genetic_background"),
		c("GFP_LFQ","cell_population","expression_capacity"),
		c("GFP_LFQ","cell_population","GFP expression"),
		c("GFP_LFQ","cellular_capacity","growth_rate","productivity"),
		c("GFP_LFQ","cellular_capacity","genetic_background","productivity"),
		c("GFP_LFQ","cellular_capacity","expression_capacity","productivity"),
		c("GFP_LFQ","cellular_capacity","GFP expression"),
		c("GFP_LFQ","cumate_induction"),
		c("GFP_LFQ","expression_capacity","GFP expression"),
		c("GFP_LFQ","genetic_background","expression_capacity"),
		c("GFP_LFQ","genetic_background","GFP expression"),
		c("GFP_LFQ","growth_rate","genetic_background"),
		c("GFP_LFQ","growth_rate","expression_capacity"),
		c("GFP_LFQ","growth_rate","GFP expression"),
		c("GFP_LFQ","plate_reader"),
		c("GFP_LFQ","productivity","GFP expression"),
		c("GFP_LFQ","proteome_expression","expression_capacity"),
		c("GFP_LFQ","proteome_expression","GFP expression"),
		c("GFP_LFQ","proteome_iBAQ","proteome_expression"),
		c("GFP_LFQ","proteome_iBAQ","expression_capacity"),
		c("GFP_LFQ","proteome_iBAQ","GFP expression"),
		c("GFP_fluorescence","GFP_iBAQ","GFP expression","proteome_expression"),
		c("GFP_fluorescence","GFP_iBAQ","GFP expression","expression_capacity"),
		c("GFP_fluorescence","GFP_iBAQ","genetic_background","GFP expression"),
		c("GFP_fluorescence","GFP_iBAQ","growth_rate","GFP expression"),
		c("GFP_fluorescence","GFP_iBAQ","cell_population","GFP expression"),
		c("GFP_fluorescence","OD","cell_population"),
		c("GFP_fluorescence","cellular_capacity","growth_rate","productivity"),
		c("GFP_fluorescence","cellular_capacity","genetic_background","productivity","cell_population"),
		c("GFP_fluorescence","cellular_capacity","expression_capacity","productivity","cell_population"),
		c("GFP_fluorescence","cellular_capacity","growth_rate","GFP expression"),
		c("GFP_fluorescence","cellular_capacity","GFP expression","cell_population"),
		c("GFP_fluorescence","cumate_induction","genetic_background","growth_rate"),
		c("GFP_fluorescence","cumate_induction","growth_rate","expression_capacity"),
		c("GFP_fluorescence","cumate_induction","cell_population","genetic_background"),
		c("GFP_fluorescence","cumate_induction","cell_population","expression_capacity"),
		c("GFP_fluorescence","cumate_induction","GFP expression","growth_rate"),
		c("GFP_fluorescence","cumate_induction","GFP expression","cell_population"),
		c("GFP_fluorescence","expression_capacity","genetic_background","GFP expression"),
		c("GFP_fluorescence","expression_capacity","growth_rate","GFP expression"),
		c("GFP_fluorescence","expression_capacity","cell_population","GFP expression"),
		c("GFP_fluorescence","genetic_background","growth_rate","expression_capacity"),
		c("GFP_fluorescence","genetic_background","cell_population","expression_capacity"),
		c("GFP_fluorescence","genetic_background","GFP expression","growth_rate"),
		c("GFP_fluorescence","genetic_background","GFP expression","cell_population"),
		c("GFP_fluorescence","growth_rate","genetic_background","cell_population"),
		c("GFP_fluorescence","growth_rate","expression_capacity","cell_population"),
		c("GFP_fluorescence","growth_rate","GFP expression","cell_population"),
		c("GFP_fluorescence","productivity","GFP expression","proteome_expression"),
		c("GFP_fluorescence","productivity","GFP expression","expression_capacity"),
		c("GFP_fluorescence","productivity","genetic_background","GFP expression"),
		c("GFP_fluorescence","productivity","growth_rate","GFP expression"),
		c("GFP_fluorescence","productivity","cell_population","GFP expression"),
		c("GFP_fluorescence","proteome_expression","expression_capacity"),
		c("GFP_fluorescence","proteome_expression","genetic_background","GFP expression"),
		c("GFP_fluorescence","proteome_expression","growth_rate","GFP expression"),
		c("GFP_fluorescence","proteome_expression","cell_population","GFP expression"),
		c("GFP_fluorescence","proteome_iBAQ","proteome_expression"),
		c("GFP_fluorescence","proteome_iBAQ","expression_capacity"),
		c("GFP_fluorescence","proteome_iBAQ","genetic_background","GFP expression"),
		c("GFP_fluorescence","proteome_iBAQ","growth_rate","GFP expression"),
		c("GFP_fluorescence","proteome_iBAQ","cell_population","GFP expression"),
		c("GFP_iBAQ","OD","cell_population"),
		c("GFP_iBAQ","OD","growth_rate"),
		c("GFP_iBAQ","OD","genetic_background"),
		c("GFP_iBAQ","OD","expression_capacity"),
		c("GFP_iBAQ","OD","proteome_expression","GFP expression"),
		c("GFP_iBAQ","cell_population","growth_rate"),
		c("GFP_iBAQ","cell_population","genetic_background"),
		c("GFP_iBAQ","cell_population","expression_capacity"),
		c("GFP_iBAQ","cell_population","proteome_expression","GFP expression"),
		c("GFP_iBAQ","cellular_capacity","growth_rate","productivity"),
		c("GFP_iBAQ","cellular_capacity","genetic_background","productivity"),
		c("GFP_iBAQ","cellular_capacity","expression_capacity","productivity"),
		c("GFP_iBAQ","cellular_capacity","proteome_expression","GFP expression"),
		c("GFP_iBAQ","cumate_induction"),
		c("GFP_iBAQ","expression_capacity","proteome_expression","GFP expression"),
		c("GFP_iBAQ","genetic_background","expression_capacity"),
		c("GFP_iBAQ","genetic_background","proteome_expression","GFP expression"),
		c("GFP_iBAQ","growth_rate","genetic_background"),
		c("GFP_iBAQ","growth_rate","expression_capacity"),
		c("GFP_iBAQ","growth_rate","proteome_expression","GFP expression"),
		c("GFP_iBAQ","plate_reader"),
		c("GFP_iBAQ","productivity","GFP expression","proteome_expression"),
		c("GFP_iBAQ","proteome_iBAQ","proteome_expression"),
		c("OD","cellular_capacity","growth_rate"),
		c("OD","cellular_capacity","cell_population"),
		c("OD","cumate_induction","growth_rate"),
		c("OD","cumate_induction","cell_population"),
		c("OD","expression_capacity","genetic_background"),
		c("OD","expression_capacity","growth_rate"),
		c("OD","expression_capacity","cell_population"),
		c("OD","genetic_background","growth_rate"),
		c("OD","genetic_background","cell_population"),
		c("OD","growth_rate","cell_population"),
		c("OD","plate_reader"),
		c("OD","productivity","GFP expression","proteome_expression"),
		c("OD","productivity","expression_capacity"),
		c("OD","productivity","genetic_background"),
		c("OD","productivity","growth_rate"),
		c("OD","productivity","cell_population"),
		c("OD","proteome_expression","expression_capacity"),
		c("OD","proteome_expression","genetic_background"),
		c("OD","proteome_expression","growth_rate"),
		c("OD","proteome_expression","cell_population"),
		c("OD","proteome_iBAQ","proteome_expression"),
		c("OD","proteome_iBAQ","expression_capacity"),
		c("OD","proteome_iBAQ","genetic_background"),
		c("OD","proteome_iBAQ","growth_rate"),
		c("OD","proteome_iBAQ","cell_population"),
		c("cell_population","cellular_capacity","growth_rate"),
		c("cell_population","cumate_induction","growth_rate"),
		c("cell_population","expression_capacity","genetic_background"),
		c("cell_population","expression_capacity","growth_rate"),
		c("cell_population","genetic_background","growth_rate"),
		c("cell_population","plate_reader"),
		c("cell_population","productivity","GFP expression","proteome_expression"),
		c("cell_population","productivity","expression_capacity"),
		c("cell_population","productivity","genetic_background"),
		c("cell_population","productivity","growth_rate"),
		c("cell_population","proteome_expression","expression_capacity"),
		c("cell_population","proteome_expression","genetic_background"),
		c("cell_population","proteome_expression","growth_rate"),
		c("cell_population","proteome_iBAQ","proteome_expression"),
		c("cell_population","proteome_iBAQ","expression_capacity"),
		c("cell_population","proteome_iBAQ","genetic_background"),
		c("cell_population","proteome_iBAQ","growth_rate"),
		c("cellular_capacity","cumate_induction","genetic_background","growth_rate"),
		c("cellular_capacity","cumate_induction","expression_capacity","growth_rate"),
		c("cellular_capacity","cumate_induction","proteome_expression","GFP expression","growth_rate"),
		c("cellular_capacity","cumate_induction","productivity","growth_rate"),
		c("cellular_capacity","expression_capacity","genetic_background","proteome_expression","GFP expression"),
		c("cellular_capacity","expression_capacity","productivity","genetic_background"),
		c("cellular_capacity","expression_capacity","growth_rate","proteome_expression","GFP expression"),
		c("cellular_capacity","expression_capacity","growth_rate","productivity"),
		c("cellular_capacity","genetic_background","growth_rate","expression_capacity"),
		c("cellular_capacity","genetic_background","growth_rate","proteome_expression","GFP expression"),
		c("cellular_capacity","genetic_background","productivity","growth_rate"),
		c("cellular_capacity","plate_reader"),
		c("cellular_capacity","proteome_expression","productivity","expression_capacity"),
		c("cellular_capacity","proteome_expression","productivity","genetic_background"),
		c("cellular_capacity","proteome_expression","growth_rate","productivity"),
		c("cellular_capacity","proteome_iBAQ","proteome_expression"),
		c("cellular_capacity","proteome_iBAQ","productivity","expression_capacity"),
		c("cellular_capacity","proteome_iBAQ","productivity","genetic_background"),
		c("cellular_capacity","proteome_iBAQ","growth_rate","productivity"),
		c("cumate_induction","expression_capacity"),
		c("cumate_induction","genetic_background"),
		c("cumate_induction","plate_reader"),
		c("cumate_induction","productivity"),
		c("cumate_induction","proteome_expression"),
		c("cumate_induction","proteome_iBAQ"),
		c("expression_capacity","growth_rate","genetic_background"),
		c("expression_capacity","plate_reader"),
		c("expression_capacity","productivity","GFP expression","proteome_expression"),
		c("expression_capacity","proteome_iBAQ","proteome_expression"),
		c("genetic_background","plate_reader"),
		c("genetic_background","productivity","GFP expression","proteome_expression"),
		c("genetic_background","productivity","expression_capacity"),
		c("genetic_background","proteome_expression","expression_capacity"),
		c("genetic_background","proteome_iBAQ","proteome_expression"),
		c("genetic_background","proteome_iBAQ","expression_capacity"),
		c("growth_rate","plate_reader"),
		c("growth_rate","productivity","GFP expression","proteome_expression"),
		c("growth_rate","productivity","expression_capacity"),
		c("growth_rate","productivity","genetic_background"),
		c("growth_rate","proteome_expression","expression_capacity"),
		c("growth_rate","proteome_expression","genetic_background"),
		c("growth_rate","proteome_iBAQ","proteome_expression"),
		c("growth_rate","proteome_iBAQ","expression_capacity"),
		c("growth_rate","proteome_iBAQ","genetic_background"),
		c("plate_reader","productivity"),
		c("plate_reader","proteome_expression"),
		c("plate_reader","proteome_iBAQ"),
		c("productivity","proteome_iBAQ","proteome_expression"))
	data.frame( implication=unlist(lapply(implications,tos)),
		pvalue=unlist( lapply( implications, tst ) ) )

}
